project:
  type: book

book:
  title: "Neural Networks...from Sratch!"
  author: "Spencer Mitchell"
  date: "3/5/2026"
  chapters:
    - index.qmd
    - chapters/slopes.ipynb
    - references.qmd

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

email-obfuscation: javascript
